name: build

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
    branches-ignore:
      # Master already has the publish workflow so avoid running twice
      - "master"

jobs:
  build:
    name: Build project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run type checking
        run: npm run typecheck
      - name: Run linting
        run: npm run lint
      - name: Build
        run: npm run build
