name: publish

on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
    branches:
      - master

jobs:
  publish:
    name: Build and deploy to Github pages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run type checking
        run: npm run typecheck
      - name: Run linting
        run: npm run lint
      - name: Build and deploy
        run: npm run build
        env:
          PUBLIC_URL: /slippi-stats
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
